# Generated by Django 2.0.13 on 2019-03-21 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('College', models.CharField(max_length=100)),
                ('Branch', models.CharField(max_length=100)),
                ('picture', models.ImageField(blank=True, default='img/default.png', null=True, upload_to='img')),
            ],
        ),
    ]
